version: "3.6"

services:

  consul:
    image: consul:1.13.2
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - asos

  git2consul:
    depends_on:
      - consul
    image: cimpress/git2consul:latest
    volumes:
      - ./config.json:/config.json
    command: --endpoint consul --port 8500 --config-file /config.json
    networks:
      - asos

  add:
    depends_on:
      - git2consul
    image: asos/add:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - asos
  gw:
    depends_on:
      - git2consul
    image: asos/gateway:latest
    ports:
      - "8080:8080"
    networks:
      - asos

networks:
  asos:
    driver: bridge
