spring:
  application:
    name: "add"
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        enabled: true
      host: consul
opentracing:
  jaeger:
    http-sender:
      url: http://jaeger:14268/api/traces
    log-spans: true
logging:
  level:
    io:
      jaegertracing: DEBUG
