spring:
  application:
    name: "add"
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        enabled: true
      host: consul
